version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db_postgress
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Use named volume to persist data
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: fastapi-backend
    depends_on:
      - db
    environment: 
     - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    networks:
      - app-network
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "8081:8080"
    volumes:
      - ./frontend:/app 
      - "/app/node_modules"
    command: 
        npm run dev
    networks:
      - app-network
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    environment:
      - VITE_API_URL= ${VITE_API_URL}

volumes:
  postgres_data:  

networks:
  app-network:
    driver: bridge
    
    