version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db_postgress
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fastapi
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Use named volume to persist data
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: fastapi-backend
    depends_on:
      - db
    environment: 
      - DATABASE_URL=postgresql://postgres:admin@172.23.224.1:5433/fastapi
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "8081:8080"
    volumes:
      - ./frontend:/app 
      - "/app/node_modules"
    environment:
      - VUE_APP_API_URL= http://172.23.224.1:8000
    command: 
        npm run dev
    networks:
      - app-network


volumes:
  postgres_data:  # Named volume for PostgreSQL data persistence

networks:
  app-network:
    driver: bridge
    
    